name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时同步一次
  workflow_dispatch: # 允许手动触发工作流程

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/<Mursor>/<LIVE>.git
          git fetch upstream
          git reset --hard upstream/main  # 将 main 分支同步到 upstream/main，根据情况更改分支名
          # git merge upstream/main  #  如果需要保留本地提交，使用 merge
          git push origin main         # 推送到你的fork仓库的main分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
